[package]
name = "voidmap"
version = "0.1.0"
authors = ["Johannes Hofmann <mail@b-r-u.org>"]
edition = "2018"

[dependencies]
env_logger = "0.8"
log = "0.4"
mio-extras = "2.0"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.2"
ws = "0.9"
